from Tkinter import *
from main import *
top = Tk()
top.minsize(height = 150, width = 500)
top.resizable(width = TRUE, height = TRUE)
id_frame = Frame(top)
id_frame.pack()
employee_id = Label(id_frame, text = 'Employee id: ')
employee_id.pack(side = LEFT)
id = Entry(id_frame, bd = 5)
id.pack(side = RIGHT)
admin_button = Button(top, text = "Admins", command = lambda: admin_rules() )
admin_button.pack(side = RIGHT)
building_frame = Frame(top)
building_frame.pack(side = TOP)
building1 = Button(building_frame, text = "B1", command = lambda: display_floor('B1', 3))
building1.pack(side = LEFT)
building2 = Button(building_frame, text = "B2", command = lambda: display_floor('B2', 2))
building2.pack(side = RIGHT)
floor_frame = Frame(top)
def display_floor(building, num_floor):
	building_frame.pack_forget()
	floor_frame.pack(side = TOP)
	Floor1 = Button(floor_frame, text = "F1", command = lambda: log_handler(building, 'F1'))
	Floor2 = Button(floor_frame, text = "F2", command = lambda: log_handler(building, 'F2'))
	Floor3 = Button(floor_frame, text = "F3", command = lambda: log_handler(building, 'F3'))
	Floor1.pack(side = LEFT)
	Floor2.pack(side = LEFT)
	if num_floor == 3:
		Floor3.pack(side = LEFT)
def log_handler(building,floor):
	floor_frame.pack_forget()
	logs_frame = Frame(top)
	logs_frame.pack(side = TOP)
	login_button = Button(logs_frame, text = "login", command = lambda: data_handler(id.get(), building, floor) )
	login_button.pack(side = LEFT)
def handler(id,building,floor):
	login_button.pack_forget()
	logout_frame = Frame(top)
	logout_button = Button(floor_frame, text = "Logout", command = lambda: logout_handler(id.get()))
	logout_button.pack()

def admin_rules():
	admin_frame = Frame(top)
	admin_frame.pack(side = TOP)
	Employee_loc = Button(admin_frame, text = "Get location", command = lambda: emp_loc_exact(id.get()))
	Employee_history = Button(admin_frame, text = "Get history", command = lambda: emp_loc_prob(id.get()))
	Employee_duration = Button(admin_frame, text = "Employee duration", command = lambda: emp_duration(id.get()))
	Floor_status = Button(admin_frame, text = "Floor Map", command = lambda: floor_map())
	Employee_loc.pack()
	Employee_history.pack()
	Employee_duration.pack()
	Floor_status.pack()

top.mainloop()
